### ISSUE TITLE
1.0 progression

### ISSUE THREAD

**Issue by natir** [natir/yacrd#12]
- [x] Multiple input #13 
- [x] Multi-threading overlapping file parsing #14
- [x] Multi-threading post-chimeric detection operation #15 
- [x] Implement post-chimeric detection:
    + [X] filtring
    + [x] spliting (only sequence data) #16 
    + [x] extracting (invert operation of filtering) #17 
- [x] Better panic message #18
- [x] Output write in json #20
